### ISSUE TITLE
okhttp3 error

### ISSUE THREAD

**Issue by MAXOUXAX** [GideonLeGrange/haveibeenpwned#2]
Hi !

I'm currently trying to use this wrapper, I used the example code to try it out, but when I instantiate my HaveIBeenPwndApi class, this error shows up.

> Exception in thread "main" java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:458)
        at me.legrange.haveibeenpwned.HaveIBeenPwndApi.<init>(HaveIBeenPwndApi.java:59)
        at me.legrange.haveibeenpwned.HaveIBeenPwndApi.<init>(HaveIBeenPwndApi.java:41)
        ...

Code » `HaveIBeenPwndApi hibp = new HaveIBeenPwndApi();`
Running the program in a git bash window.
Using Windows 10, Java 8, imported the depend using Maven.

Looking forward for an answer,
Maxx_.

**Comment by MAXOUXAX** [comment]
@GideonLeGrange
